name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on:
  push:
    tags:
      - '*'

jobs:
  build:

    name: Build and Test the Python distribution
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64
    environment:
      name: pypi
      url: https://pypi.org/p/random_events  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:

    - name: Checkout the code
      uses: actions/checkout@v1
      with:
        submodules: 'true'

    - name: Update submodules
      run: |
        git config --global --add safe.directory '*'
        git submodule update --init --recursive

    - name: Build for Python3.8
      run: |
        python3.8 -m pip install --upgrade pip
        python3.8 -m pip  install wheel setuptools pip --upgrade
        python3.8 -m pip  install -r requirements.txt
        python3.8 -m pip  install build twine
        python3.8 -m pip wheel . -w dist/


    - name: Build for Python3.9
      run: |
        python3.9 -m pip install --upgrade pip
        python3.9 -m pip  install wheel setuptools pip --upgrade
        python3.9 -m pip  install -r requirements.txt
        python3.9 -m pip  install build twine
        python3.9 -m pip wheel . -w dist/

    - name: Build for Python3.10
      run: |
        python3.10 -m pip install --upgrade pip
        python3.10 -m pip  install wheel setuptools pip --upgrade
        python3.10 -m pip  install -r requirements.txt
        python3.10 -m pip  install build twine
        python3.10 -m pip wheel . -w dist/

    - name: Build for Python3.11
      run: |
        python3.11 -m pip install --upgrade pip
        python3.11 -m pip  install wheel setuptools pip --upgrade
        python3.11 -m pip  install -r requirements.txt
        python3.11 -m pip  install build twine
        python3.11 -m pip wheel . -w dist/

    - name: Build for Python3.12
      run: |
        python3.12 -m pip install --upgrade pip
        python3.12 -m pip  install wheel setuptools pip --upgrade
        python3.12 -m pip  install -r requirements.txt
        python3.12 -m pip  install build twine
        python3.12 -m pip wheel . -w dist/

    - name: Clean up dist
      run: |
        cd dist/
        find . ! -name 'random_events*' -type f -exec rm -f {} +
        cd ..

    - name: Repair wheel
      run: |
        auditwheel repair dist/*.whl
        rm dist/*.whl
        mv wheelhouse/*.whl dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1.11
      with:
        skip_existing: false

