name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on: push

jobs:
  build:
    name: Build and Test the Python distribution
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout 🛎
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      # ----------------------------------------------------------------------------------------------------------------

      - name: Setup python 🐍
        uses: actions/setup-python@v4
        with:
            python-version: "3.9"
            cache: pip
            
      # ----------------------------------------------------------------------------------------------------------------

      - name: Install user dependencies 🍼
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements-dev.txt"

      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  
      - name: Build
        # Build your program with the given configuration
        # run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        run: |
          python3.9 -m build --wheel -n
          
      - name: Repair wheel
        run: |
            auditwheel repair dist/*.whl
            rm dist/*.whl
            mv wheelhouse/*.whl dist/
  
  publish-to-pypi:
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/random_events  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
