name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and Test the Python distribution
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/random_events  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:

    - name: Checkout the code
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools pip --upgrade
        pip install -r requirements.txt
        pip install build twine

    - name: Build the distribution 📦
      run: |
          pip wheel . -w dist/

    - name: Clean up dist
      run: |
        cd dist/
        rm -- !(random_events*)
        cd ..

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip_existing: false

