name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on: push

jobs:
  build:
    name: Build and Test the Python distribution
    runs-on: ubuntu-latest

    container:
        image: quay.io/pypa/manylinux2014_x86_64
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    environment: release

  
    steps:

      - name: Checkout 🛎
        uses: actions/checkout@v1
        with:
          submodules: 'true'
      # ----------------------------------------------------------------------------------------------------------------

      # - name: Install user dependencies 🍼
      #   uses: py-actions/py-dependency-install@v1
      #   with:
      #     path: "requirements-dev.txt"

      - name: Install Buildtools
        run: |
          python3.8 -m pip install setuptools build numpy
          python3.9 -m pip install setuptools build numpy
          python3.10 -m pip install setuptools build numpy
          python3.11 -m pip install setuptools build numpy
          python3.12 -m pip install setuptools build numpy


      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          
      - name: Build
      # Build your program with the given configuration
      # run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
        run: |
          python3.8 -m build --wheel -n
          python3.9 -m build --wheel -n
          python3.10 -m build --wheel -n
          python3.11 -m build --wheel -n
          python3.12 -m build --wheel -n
  
  publish-to-pypi:
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/random_events  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
