name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and Test the Python distribution
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_34_x86_64
    environment:
      name: pypi
      url: https://pypi.org/p/random_events  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Update submodules
        run: |
          git config --global --add safe.directory '*'
          git submodule update --init --recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools pip --upgrade
          pip install -r requirements.txt
          pip install build twine

      - name: Build the distribution 📦
        run: |
          python -m pip wheel . -w dist/

      - name: Clean up dist
        run: |
          cd dist/
          find . ! -name 'random_events*' -type f -exec rm -f {} +
          cd ..

      - name: Repair wheel
        run: |
          auditwheel repair dist/*.whl
          rm dist/*.whl
          mv wheelhouse/*.whl dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: false